### ISSUE TITLE
Create good user experience to the user flow

### ISSUE THREAD

**Issue by welisonmenezes** [welisonmenezes/sysead#57]
@SandroVingla 

- [x] At page 'listar' add a filter containing 'Nome', 'Matrícula', 'Tipo' and 'Status' fields. The fields 'Matricula' and 'Status' must be a combobox.
- [x] At page 'listar' change button text 'Cadastrar Novo Usuário' to 'Adicionar Novo' and add a plus icon.
- [x] At page 'listar' change the buttons 'Ver' to a button with eye icon.
- [x] At page 'cadastrar' remove the title 'Cadastrar Usuário', the bigger one.
- [x] At page 'cadastrar', 'ver' and 'editar' put the button 'Voltar' at the first place on the left.
- [x] At page 'cadastrar', 'ver' and 'editar', increase the left column of the grid and decrease the right one.
- [x] At page 'ver' add a confirmation modal to be opened when the button 'deletar' was clicked.
- [x] At page 'ver' include a eye icon button to each row of the right table 'Turmas'. Also include a modal to be opened when this button was clicked. (see page 'ver' of 'Disciplinas' flow).
- [ ] Add in page 'editar' a copy of the right table that exists at page 'ver'.

Take your time. Be calm.

**Comment by SandroVingla** [comment]
close #59
